apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: find-pepe
build:
  artifacts:
    - image: app
      context: services/app
      docker:
        dockerfile: Dockerfile
    - image: scraper
      context: services/scraper
      docker:
        dockerfile: Dockerfile
    - image: vision
      context: services/vision
      docker:
        dockerfile: Dockerfile
    - image: server
      context: services/server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/common/namespaces.yaml
    - k8s/common/pv.yaml
    - k8s/common/pvc.yaml
    - k8s/common/ingress.yaml
    - k8s/app/deployment.yaml
    - k8s/app/service.yaml
    - k8s/scraper/cronjob.yaml
    - k8s/server/deployment.yaml
    - k8s/server/service.yaml
    - k8s/vision/deployment.yaml
    - k8s/vision/service.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: ingress-nginx
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
