apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: find-pepe
build:
  artifacts:
    - image: app
      context: services/app
      docker:
        dockerfile: Dockerfile
    - image: scraper
      context: services/scraper
      docker:
        dockerfile: Dockerfile
    - image: vision
      context: services/vision
      docker:
        dockerfile: Dockerfile
    - image: server
      context: services/server
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/common/namespaces.yaml
    - k8s/common/pv.yaml
    - k8s/common/pvc.yaml
    - k8s/common/ingress.yaml
    - k8s/app/deployment.yaml
    - k8s/app/service.yaml
    - k8s/scraper/cronjob.yaml
    - k8s/server/deployment.yaml
    - k8s/server/service.yaml
    - k8s/vision/deployment.yaml
    - k8s/vision/service.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: ingress-nginx
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
      - name: postgresql
        version: 12.10.0
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        setValues:
          primary.persistence.existingClaim: pepe-pvc
          primary.persistence.subPath: db
          primary.persistence.mountPath: /bitnami/postgresql
          global.postgresql.auth.postgresPassword: "test"
          global.postgresql.auth.username: "admin"
          global.postgresql.auth.password: "test"
        namespace: find-pepe
        createNamespace: false
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
