apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-cronjob
  labels:
    app: scraper
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: scraper
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scraper
            image: scraper:latest
            resources:
              limits:
                memory: 512Mi
                cpu: 200m
            env:
            - name: VISION_API_URL
              value: http://vision:5000
