# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   namespace: find-pepe
#   name: scraper-cronjob
#   labels:
#     app: scraper
# spec:
#   schedule: "* * * * *"
#   jobTemplate:
#     metadata:
#       labels:
#         app: scraper
#     spec:
#       template:
#         spec:
#           restartPolicy: OnFailure
#           containers:
#           - name: scraper
#             image: scraper:latest
#             resources:
#               limits:
#                 memory: 2Gi
#                 cpu: 1000m
#             env:
#             - name: VISION_API_URL
#               value: http://vision:5000
#             - name: IMAGE_LIMIT
#               value: "50"
#             - name: CLASSIFY_LIMIT
#               value: "50"
#             - name: HTML_LIMIT
#               value: "100"
#             volumeMounts:
#             - name: volume
#               mountPath: /app/data/
#           volumes:
#           - name: volume
#             persistentVolumeClaim:
#               claimName: pepe-pvc
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: find-pepe
  labels:
    app: scraper-deployment
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  strategy: {}
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: scraper:latest
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
        env:
        - name: VISION_API_URL
          value: http://vision:5000
        - name: IMAGE_LIMIT
          value: "0"
        - name: CLASSIFY_LIMIT
          value: "0"
        - name: HTML_LIMIT
          value: "0"
        - name: "POSTGRES_HOST"
          value: "postgresql"
        - name: "POSTGRES_PASSWORD"
          value: "test"
        - name: "POSTGRES_USER"
          value: "admin"
        volumeMounts:
        - name: volume
          mountPath: /app/data/
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: pepe-pvc
status: {}
