apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: find-pepe
  labels:
    app: vision
  name: vision
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vision
  strategy: {}
  template:
    metadata:
      labels:
        app: vision
    spec:
      containers:
      - image: vision:latest
        ports:
        - name: http-vision
          containerPort: 5000
          protocol: TCP
        name: vision
        resources:
          limits:
            memory: 2Gi
            cpu: 200m
status: {}
