apiVersion: v1
kind: PersistentVolume
metadata:
  name: pepe-pv
  labels:
    type: local
  namespace: find-pepe
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data