apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pepe-pvc
  namespace: find-pepe
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi